add checksum verification

diff --git a/.github/workflows/python-lint-test-upload.yml b/.github/workflows/python-lint-test-upload.yml
--- a/.github/workflows/python-lint-test-upload.yml
+++ b/.github/workflows/python-lint-test-upload.yml
@@ -22,9 +22,17 @@ jobs:
       with:
         python-version: ${{ matrix.python-version }}
 
+    - name: Download Task & Verify Checksum
+      run: |
+        wget https://github.com/go-task/task/releases/download/v3.30.1/task_linux_amd64.deb
+        echo "22f29aba72c80ca3e974bc86da0ad46ba4e5098b4b7435cdf88b83ed603c3c48 task_linux_amd64.deb" | sha256sum --check --status
+        if [ $? -ne 0 ]; then echo "Checksum verification failed!"; exit 1; fi
+    
     - name: Install Task
       run: |
-          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
+        sudo dpkg -i task_linux_amd64.deb
+        sudo apt-get install -f
+
 
     - name: Install and upgrade pip and poetry
       run: |
